name: First Work flow
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        uses: actions/checkout@v4
      - name: Second step
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4
      - name: Third step
        run: terraform fmt
      - name: Fifth step
        run: terraform init